version: '3.9'
services:
  rag_bot:
    image: myfastapi-ml-app:latest
    container_name: rag_bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env